spring:
  application:
    name: file-service
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    log-request-details: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://MysqlIp:3306/rent_file?useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: 你的密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      login-timeout: 5
      idle-timeout: 60000
      connection-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 10
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  cloud:
    alibaba:
      seata:
        tx-service-group: rent_tx_group
server:
  port: 53080
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  use-forward-headers: true


eureka:
  client:
    service-url:
      defaultZone: http://IP:53000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

aliyun:
  accessId: 阿里云id
  accessKey: 你的密码
  bucket: bucket名
  endpoint: 端点名
  url: 域名
#保存路径
file:
  rootPath: 保存根路径
  imgPath: img/
  housePath: house/
  userPath: user/
  videoPath: video/
  contractPath: contract/
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000  # 设置熔断超时时间  default 1000
        timeout:
          enabled: true # 打开超时熔断功能 default true


ribbon:
  ConnectTimeout: 600 # 设置连接超时时间 default 2000
  ReadTimeout: 6000    # 设置读取超时时间  default 5000
  OkToRetryOnAllOperations: true # 对所有操作请求都进行重试  default false
  MaxAutoRetriesNextServer: 2    # 切换实例的重试次数  default 1
  MaxAutoRetries: 1     # 对当前实例的重试次数 default 0

