spring:
  application:
    name: uaa-service
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://MysqlIp:3306/rent_user?useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: 你的密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      login-timeout: 5
      idle-timeout: 60000
      connection-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 10
server:
  port: 53020
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  use-forward-headers: true


feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: ['text/xml','application/xml','application/json']
      min-request-size: 2048
    response:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://IP:53000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}