spring:
  application:
    name: user-service
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    log-request-details: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://MysqlIp:3306/rent_user?useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: 你的密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      login-timeout: 5
      idle-timeout: 60000
      connection-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 500
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  rabbitmq:
    host: RabbitMQIP
  cloud:
    alibaba:
      seata:
        tx-service-group: rent_tx_group


server:
  port: 53070
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  use-forward-headers: true

eureka:
  client:
    service-url:
      defaultZone: http://IP:53000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


feign:
  hystrix:
    enabled: true

aliyun:
  accessId: 阿里云id
  accessKey: 你的密码
  bucket: bucket名
  endpoint: 端点名
  url: url
#保存路径
file:
  imgPath: img/
  housePath: house/
  userPath: user/
  videoPath: video/
  contractPath: contract/