spring:
  application:
    name: discovery
server:
  port: 53000 #启动端口
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #eureka server管理页面显示的服务状态
    prefer-ip-address: true
  server:
    enable-self-preservation: false    #关闭服务器自我保护，客户端心跳检测15分钟内错误达到80%服务会保护，导致别人还认为是好用的服务
    eviction-interval-timer-in-ms: 10000 #清理间隔（单位毫秒，默认是60*1000）5秒将客户端剔除的服务在服务注册列表中剔除#
    shouldUseReadOnlyResponseCache: true #eureka是CAP理论种基于AP策略，为了保证强一致性关闭此切换CP 默认不关闭 false关闭
  client:
    fetch-registry: false
    register-with-eureka: false
    instance-info-replication-interval-seconds: 10
    service-url:
      defaultZone:  http://IP:${server.port}/eureka/
